language: python

python:
  - "3.7"

services:
  - postgresql

before_script:
  - pip install pipenv
  - pipenv install
  - pipenv install coverage
  - psql -c 'CREATE DATABASE travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - pytest

after_script:
  - coverage report
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
